# Generated by Django 5.0.5 on 2024-05-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='engine_type',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='transmission_type',
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_type',
            field=models.CharField(choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('WAGON', 'Wagon'), ('COUPE', 'Coupe'), ('CONVERTIBLE', 'Convertible')], default='SUV', max_length=15),
        ),
    ]
