# Generated by Django 5.0.4 on 2024-05-04 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='car_type',
            new_name='type',
        ),
    ]
